//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gda_passport
    {
        public int Id { get; set; }
        public int id_user { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public string born { get; set; }
        public string kingdom { get; set; }
        public string gender { get; set; }
        public string marital_status { get; set; }
        public string family_surname { get; set; }
        public string family_name { get; set; }
        public string family_patronymic { get; set; }
        public string family_who_registered { get; set; }
        public string family_when_registered { get; set; }
        public string mom_surname { get; set; }
        public string mom_name { get; set; }
        public string mom_patronymic { get; set; }
        public string father_surname { get; set; }
        public string father_name { get; set; }
        public string father_patronymic { get; set; }
        public string residence_city { get; set; }
        public string residence_house { get; set; }
        public string residence_apartment { get; set; }
        public string foreign_citizenship { get; set; }
        public string foreign_citizenship_where { get; set; }
        public string foreign_citizenship_now { get; set; }
        public string reason_for_issuing { get; set; }
        public string date_of_filling { get; set; }
    }
}
