//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kabinets
    {
        public int KabinetId { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string SurName { get; set; }
        public string Patshroryk { get; set; }
        public System.DateTime DateOfBirths { get; set; }
        public string PlaseOfBirds { get; set; }
        public string PlaseOfRegistration { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Phone { get; set; }
    }
}
