<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-MvcApplication1-20141021183026" Class="PassportModelsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\aspnet-MvcApplication1-20141021183026.mdf;Initial Catalog=aspnet-MvcApplication1-20141021183026;Integrated Security=True;MultipleActiveResultSets=True;Application Name=EntityFramework" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspnet_MvcApplication1_20141021183026ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.gda_passport" Member="gda_passport">
    <Type Name="gda_passport">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_user" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="patronymic" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="born" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="kingdom" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="marital_status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="family_surname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="family_name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="family_patronymic" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="family_who_registered" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="family_when_registered" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="mom_surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mom_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mom_patronymic" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="father_surname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="father_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="father_patronymic" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="residence_city" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="residence_house" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="residence_apartment" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="foreign_citizenship" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="foreign_citizenship_where" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="foreign_citizenship_now" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="reason_for_issuing" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="date_of_filling" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="webpages_Membership_gda_passport" Member="webpages_Membership" ThisKey="id_user" OtherKey="UserId" Type="webpages_Membership" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.webpages_Membership" Member="webpages_Membership">
    <Type Name="webpages_Membership">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ConfirmationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LastPasswordFailureDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordFailuresSinceLastSuccess" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordChangedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordVerificationToken" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="PasswordVerificationTokenExpirationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="webpages_Membership_gda_passport" Member="gda_passport" ThisKey="UserId" OtherKey="id_user" Type="gda_passport" />
    </Type>
  </Table>
</Database>